"""add owner, shelter, pet

Revision ID: 01b56c6f9961
Revises: 
Create Date: 2025-02-03 11:56:04.322047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b56c6f9961'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shelters_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pets_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('shelter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners_table.id'], name=op.f('fk_pets_table_owner_id_owners_table')),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelters_table.id'], name=op.f('fk_pets_table_shelter_id_shelters_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets_table')
    op.drop_table('shelters_table')
    op.drop_table('owners_table')
    # ### end Alembic commands ###
